#!/bin/bash
#SBATCH --job-name=run_ortho_finder       # Job name
#SBATCH --partition=schmitz_hm_p               # Partition (queue) name, i.e., highmem_p
#SBATCH --ntasks=1                          # Run a single task
#SBATCH --cpus-per-task=28                  # Number of CPU cores per task
#SBATCH --mem=120gb                          # Job memory request
#SBATCH --time=12:00:00                     # Time limit hrs:min:sec
#SBATCH --output=log_all_plants_ortho_finder.subset.%j.out         # Standard output log
#SBATCH --error=log_all_plants_ortho_finder.subset.%j.err          # Standard error log
#SBATCH --mail-type=END,FAIL                # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=john.mendieta@uga.edu   # Where to send mail
#SBATCH --export=NONE                       # do not load any env variables to compute node
